config/routes.rb
Rails.application.routes.draw do
  resources :careers do
    resources :requirements, except: [:index, :show]
    get 'panorama', on: :member
  end
  resources :acquirements, except: [:show]
  resources :hackers
  resources :skills

  root 'welcome#index'
  post 'login' => 'sessions#create', as: 'login'
  match 'signout' => 'sessions#destroy', via: [:get, :delete]

end

app/models/acquirement.rb
require 'experience_level'

class Acquirement < ActiveRecord::Base
  belongs_to :hacker
  belongs_to :skill

  validates :level, presence: true
  validates :skill_id, presence: true, uniqueness: { scope: :hacker_id }

  def level
    ExperienceLevel.new(super)
  end
end

app/models/career.rb
require 'seniority'

class Career < ActiveRecord::Base
  has_many :hackers
  has_many :requirements

  def get_seniority acquirements
    missing_requirements(acquirements).map(&:seniority).min.previous
  end

  def missing_requirements acquirements
    @missing_requirements ||= requirements.reject do |requirement|
      acquirements.any? do |acquirement|
        requirement.skill_id == acquirement.skill_id && acquirement.level >= requirement.level
      end
    end
  end
end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  has_secure_password
  has_many :acquirements
  has_many :skills, through: :acquirements
  belongs_to :career

  validates :career_id, presence: true

  def seniority
    career.get_seniority acquirements unless id.nil?
  end

  def missing_requirements_for_next_seniority
    career.missing_requirements(acquirements).keep_if do |r|
      r.seniority == seniority.next
    end
  end
end

app/models/requirement.rb
require 'experience_level'

class Requirement < ActiveRecord::Base
  belongs_to :career
  belongs_to :skill

  validates :level, presence: true
  validates :skill_id, presence: true, uniqueness: { scope: :seniority }

  def level
    ExperienceLevel.new(super)
  end

  def seniority
    Seniority.new(super)
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/controllers/acquirements_controller.rb
class AcquirementsController < ApplicationController
  before_action :set_acquirement, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @acquirements = acquirements
  end

  def new
    @acquirement = acquirements.new
  end

  def edit
  end

  def create
    @acquirement = acquirements.create acquirement_params
    respond_with(@acquirement, location: new_acquirement_path)
  end

  def update
    @acquirement.update(acquirement_params)
    respond_with(@acquirement, location: acquirements_path)
  end

  def destroy
    @acquirement.destroy
    respond_with(@acquirement)
  end

  private
    def acquirements
      current_hacker.acquirements
    end

    def set_acquirement
      @acquirement = acquirements.find(params[:id])
    end

    def acquirement_params
      params.require(:acquirement).permit(:level, :hacker_id, :skill_id)
    end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_authentication
  helper_method :current_hacker

  private

    def require_authentication
      redirect_to root_url, alert: 'Login required' unless session[:hacker_id]
    end

    def current_hacker
      @current_hacker ||= Hacker.find session[:hacker_id] if session[:hacker_id]
    end
end

app/controllers/careers_controller.rb
require 'panorama'

class CareersController < ApplicationController
  before_action :set_career, only: [:show, :edit, :update, :destroy, :panorama]

  respond_to :html

  def index
    @careers = Career.all
    respond_with(@careers)
  end

  def show
    respond_with(@career)
  end

  def new
    @career = Career.new
    respond_with(@career)
  end

  def edit
  end

  def create
    @career = Career.new(career_params)
    @career.save
    respond_with(@career)
  end

  def update
    @career.update(career_params)
    respond_with(@career)
  end

  def destroy
    @career.destroy
    respond_with(@career)
  end

  def panorama
    @panorama = Panorama.new @career
    respond_with(@panorama)
  end

  private
    def set_career
      @career = Career.find(params[:id])
    end

    def career_params
      params.require(:career).permit(:name, :description)
    end
end

app/controllers/hackers_controller.rb
require 'hacker_inviter'

class HackersController < ApplicationController
  before_action :set_hacker, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @hackers = Hacker.all
    respond_with(@hackers)
  end

  def show
    respond_with(@hacker)
  end

  def new
    @hacker = Hacker.new
    respond_with(@hacker)
  end

  def edit
  end

  def create
    @hacker = HackerInviter.new(hacker_params).hacker
    respond_with(@hacker)
  end

  def update
    @hacker.update(hacker_params)
    respond_with(@hacker)
  end

  def destroy
    @hacker.destroy
    respond_with(@hacker)
  end

  private
    def set_hacker
      @hacker = Hacker.find(params[:id])
    end

    def hacker_params
      params.require(:hacker).permit(:name, :email, :career_id, :seniority,
                                     :password, :password_confirmation)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:edit, :update, :destroy]
  before_action :set_career

  respond_to :html

  def new
    @requirement = new_requirement
    respond_with(@requirement)
  end

  def edit
  end

  def create
    @requirement = new_requirement requirement_params
    @requirement.save
    respond_with(@requirement, location: career_path(@career))
  end

  def update
    @requirement.update(requirement_params)
    respond_with(@requirement, location: career_path(@career))
  end

  def destroy
    @requirement.destroy
    respond_with(@requirement, location: career_path(@career))
  end

  private

    def set_career
      @career = Career.find(params[:career_id])
    end

    def new_requirement attributes={}
      @requirement = Career.find(params[:career_id]).requirements.new attributes
    end

    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    def requirement_params
      params.require(:requirement).permit(:level, :seniority, :skill_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_authentication

  def create
    hacker = Hacker.find_by(email: params[:email])
      .try(:authenticate, params[:password])
    if hacker
      session[:hacker_id] = hacker.id
      flash.notice = 'Successfully logged in'
    else
      flash.alert = 'Invalid email or password'
    end
    redirect_to root_url
  end

  def destroy
    session.clear
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @skills = Skill.all
    respond_with(@skills)
  end

  def show
    respond_with(@skill)
  end

  def new
    @skill = Skill.new
    respond_with(@skill)
  end

  def edit
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.save
    respond_with(@skill)
  end

  def update
    @skill.update(skill_params)
    respond_with(@skill)
  end

  def destroy
    @skill.destroy
    respond_with(@skill)
  end

  private
    def set_skill
      @skill = Skill.find(params[:id])
    end

    def skill_params
      params.require(:skill).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_authentication

  def index
    render :dashboard if current_hacker
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def md5 string
    Digest::MD5.hexdigest string
  end

  def assign_class requirement, acquirement
    if acquirement.nil? || requirement.level > (acquirement.level + 1)
      "not-accomplished"
    else
      "almost-accomplished"
    end
  end

  def gravatar_url hacker
    'http://www.gravatar.com/avatar/' + md5(hacker.email)
  end

  def current_hacker_gravatar
    image_tag(gravatar_url(current_hacker), class: 'avatar')
  end
end

app/views/acquirements/_form.html.erb
<%= form_for(@acquirement) do |f| %>
  <% if @acquirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acquirement.errors.count, "error") %> prohibited this acquirement from being saved:</h2>

      <ul>
      <% @acquirement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill %>
    <%= f.skill_select %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.experience_level_select %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acquirements/edit.html.erb
<h1>Editing Acquirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @acquirement %> |
<%= link_to 'Back', acquirements_path %>

app/views/acquirements/index.html.erb
<h1>Listing Acquirements</h1>

<ul class="acquirements">
  <% @acquirements.each do |acquirement| %>
    <li>
      <h3><%= acquirement.skill.name %></h3>
      <p>Current Level: <%= acquirement.level %></p>
      <%= link_to 'Edit', edit_acquirement_path(acquirement) %>
      <%= link_to 'Destroy', acquirement, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>

  <li class="content-center">
    <%= link_to 'New Acquirement', new_acquirement_path %>
  </li>
</ul>

app/views/acquirements/new.html.erb
<h1>New Acquirement</h1>

<%= render 'form' %>

<%= link_to 'Back', acquirements_path %>

app/views/application/_navbar.html.erb
<nav>
  <!-- img src="assets/logo.svg" alt="Hacker Assessor" class="logo" -->
  <%= link_to root_path, class: 'button' do %>
    <h1 class="logo">Hacker Assessor</h1>
  <% end %>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>

  <% if current_hacker %>
    <%= link_to current_hacker_gravatar + 'LOGOUT',
                signout_path, method: :delete, class: 'button' %>
    <%= link_to 'Acquirements', acquirements_path, class: 'button' %>
    <%= link_to 'Skills', skills_path, class: 'button' %>
    <%= link_to 'Careers', careers_path, class: 'button' %>
    <%= link_to 'Invite', new_hacker_path, class: 'button' %>
  <% else %>
    <%= form_tag login_path do |f| %>
      <%= text_field_tag :email, nil, placeholder: 'Email' %>
      <%= password_field_tag :password, nil, placeholder: 'Password' %>
      <%= submit_tag 'LOG IN' %>
      <a href="#">Forgot your password?</a>
    <% end %>
  <% end %>
</nav>

app/views/careers/_form.html.erb
<%= form_for(@career) do |f| %>
  <% if @career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@career.errors.count, "error") %> prohibited this career from being saved:</h2>

      <ul>
      <% @career.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/careers/edit.html.erb
<h1>Editing Career</h1>

<%= render 'form' %>

<%= link_to 'Back', careers_path %>

app/views/careers/index.html.erb
<h1>Listing Careers</h1>

<ul class="careers">
  <% @careers.each do |career| %>
    <li>
      <%= link_to career do %>
        <h2><%= career.name %></h2>
        <%= career.description %>
      <% end %>
      <%= link_to 'Panorama', panorama_career_path(career) %>
    </li>
  <% end %>

  <li class="content-center">
    <%= link_to 'New Career', new_career_path %>
  </li>
</ul>

app/views/careers/new.html.erb
<h1>New Career</h1>

<%= render 'form' %>

<%= link_to 'Back', careers_path %>

app/views/careers/panorama.html.erb
<h1><%= @career.name %> career</h1>

<table class="panorama">
  <thead>
    <tr>
      <th>Skill</th>
      <% Seniority::NAMES.each do |seniority| %>
        <th><%= seniority %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @panorama.each_skill do |requirement| %>
      <tr>
        <td><%= Skill.find(requirement[:skill_id]).name %></td>
        <% requirement[:requirements_levels].each do |level| %>
          <td><%= level %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', careers_path %>

app/views/careers/show.html.erb
<h2><%= @career.name %></h2>

<p><%= @career.description %></p>

<ul class="requirements">
  <% @career.requirements.each do |requirement| %>
    <li>
      <h3><%= requirement.skill.name %></h3>
      <p>Required level: <%= requirement.level %></p>
      <p>For seniority: <%= requirement.seniority %></p>
      <%= link_to 'Edit', edit_career_requirement_path(@career, requirement) %>
      <%= link_to 'Destroy', [@career, requirement], method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>

  <li class="content-center">
    <%= link_to 'New requirement', new_career_requirement_path(@career) %>
  </li>
</ul>

<%= link_to 'Edit', edit_career_path(@career) %> |
<%= link_to 'Destroy', career_path(@career), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', careers_path %>

app/views/hackers/_form.html.erb
<%= form_for(@hacker) do |f| %>
  <% if @hacker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hacker.errors.count, "error") %> prohibited this hacker from being saved:</h2>

      <ul>
      <% @hacker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :career_id %>
    <%= f.select :career_id, Career.all.collect { |p| [ p.name, p.id  ] } %>
  </div>
  <div class="field">
    <%= f.label :seniority %>
    <%= f.seniority_select %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hackers/edit.html.erb
<h1>Editing Hacker</h1>

<%= render 'form' %>

<%= link_to 'Show', @hacker %> |
<%= link_to 'Back', hackers_path %>

app/views/hackers/index.html.erb
<h1>Listing Hackers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hackers.each do |hacker| %>
      <tr>
        <td><%= hacker.name %></td>
        <td><%= hacker.email %></td>
        <td><%= link_to 'Show', hacker %></td>
        <td><%= link_to 'Edit', edit_hacker_path(hacker) %></td>
        <td><%= link_to 'Destroy', hacker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hacker', new_hacker_path %>

app/views/hackers/new.html.erb
<h1>New Hacker</h1>

<%= render 'form' %>

<%= link_to 'Back', hackers_path %>

app/views/hackers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @hacker.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @hacker.email %>
</p>

<%= link_to 'Edit', edit_hacker_path(@hacker) %> |
<%= link_to 'Back', hackers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>Hacker Assessor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>

<section>
  <%= render 'navbar' %>
  <main>
    <%= yield %>
    <footer>
      Made with mate in Santa Fe, Argentina.
      &copy; 2015 Altoros.
      Under <a href="https://www.gnu.org/licenses/agpl">AGPL</a>.
      Get the <a href="https://github.com/Altoros/hacker-assessor">source</a>
    </footer>
  </main>
</section>

</body>
</html>

app/views/requirements/_form.html.erb
<%= form_for([@requirement.career, @requirement]) do |f| %>
  <% if @requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
      <% @requirement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill_id %>
    <%= f.skill_select %>
  </div>
  <div class="field">
    <%= f.label :level %>
    <%= f.experience_level_select %>
  </div>
  <div class="field">
    <%= f.label :seniority %>
    <%= f.seniority_select %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requirements/_requirement.html.erb
<% acquirement = current_hacker.acquirements.find_by(skill: requirement.skill) %>
<li class="<%= assign_class requirement, acquirement %>">
  <h3><%= requirement.skill.name %></h3>
  <p>Required level: <%= requirement.level %></p>
  <% if acquirement %>
    <p>Your level: <%= acquirement.level %></p>
  <% end %>
</li>

app/views/requirements/edit.html.erb
<h1>Editing Requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', career_path(@requirement.career) %>

app/views/requirements/index.html.erb
<h1>Listing Requirements</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Seniority</th>
      <th>Skill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requirements.each do |requirement| %>
      <tr>
        <td><%= requirement.level %></td>
        <td><%= requirement.seniority %></td>
        <td><%= requirement.skill %></td>
        <td><%= link_to 'Show', requirement %></td>
        <td><%= link_to 'Edit', edit_requirement_path(requirement) %></td>
        <td><%= link_to 'Destroy', requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requirement', new_requirement_path %>

app/views/requirements/new.html.erb
<h1>New Requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', career_path(@requirement.career) %>

app/views/skills/_form.html.erb
<%= form_for(@skill) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Listing Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.description %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>

app/views/welcome/dashboard.html.erb
<h1>Welcome <%= current_hacker.name %></h1>
<p><strong>Your current seniority is</strong>:
   <%= current_hacker.seniority %> in the career of <%= current_hacker.career.name %>.</p>
<h1>To reach <%= current_hacker.seniority.next %> this are the missing skills:</h1>

<ul class="requirements">
  <%= render current_hacker.missing_requirements_for_next_seniority %>
</ul>

app/views/welcome/index.html.erb
<p>Hacker Assessor is a service and an on-premise tool for managing software teams
consistently based on data provided by each software team member within any given
project requirements.</p>

<p>By integrating with social data from services hackers already use such as GitHub
and Stack Overflow, Hacker Assessor will allow project leaders to get a good overview
of each of its team member’s strengths and weaknesses. Also, this tool will allow
team leaders to take action by offering suggestions about how to improve where
it’s lacking.</p>

<h1> GET STARTED!</h1>

<%= link_to 'SIGN UP NOW!' %>
or
<%= link_to 'FORK ME ON GITHUB!' %>

<p>Hacker Assesor is an Open Source project sponsored by Altoros.</p>